version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx_debian
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/wordpress

  wordpress:
    image: wordpress
    container_name: wordpress_debian
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/wordpress

  mariadb:
    image: mariadb
    container_name: mariadb_debian
    build: ./requirements/mariadb
    restart: always
    networks:
      - inception_network
    volumes:
      - mariadb_volume:/var/lib/mysql

networks:
  inception_network:

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dodjian/data/wordpress_volume
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dodjian/data/mariadb_volume
